{
	"swagger": "2.0",
	"info": {
		"title": "Dynamics365",
		"description": "API for trial-jjl7u0.sandbox.operations.dynamics.com",
		"version": "0.0.0"
	},
	"host": "trial-jjl7u0.sandbox.operations.dynamics.com",
	"basePath": "/data",
	"schemes": [
		"https"
	],
	"paths": {
		"/CustomersV3": {
			"post": {
				"tags": [
					"CustomersV3"
				],
				"summary": "Create a Customer",
				"description": "Create a Customer",
				"operationId": "CreateCustomer",
				"consumes": [
					"application/json"
				],
				"produces": [
					"application/json"
				],
				"parameters": [
					{
						"name": "Authorization",
						"in": "header",
						"description": "Authorization",
						"required": true,
						"type": "string",
						"x-example": ""
					},
					{
						"name": "Customer",
						"in": "body",
						"description": "Customer",
						"required": true,
						"schema": {
							"$ref": "#/definitions/Customer"
						}
					},
					{
						"name": "Accept",
						"in": "header",
						"description": "Accept",
						"required": false,
						"default": "application/json",
						"type": "string",
						"x-example": ""
					}
				],
				"responses": {
					"200": {
						"description": "OK",
						"schema": {
							"$ref": "#/definitions/Customer"
						},
						"examples": {
							"application/json": {
								"@odata.context": "https://trial-jjl7u0.sandbox.operations.dynamics.com/data/$metadata#CustomersV3/$entity",
								"@odata.etag": "W/\"JzEsNjg3MTk0ODUzMDg7MCwwOzAsMDswLDA7MSw2ODcxOTUxODc2NDsxLDY4NzE5NTIyOTc2OzAsMDswLDA7MCwwOzAsMDswLDAn\"",
								"dataAreaId": "dat",
								"CustomerAccount": "CA00000021",
								"AddressBrazilianCNPJOrCPF": "",
								"PartyType": "Organization",
								"PrimaryContactFaxExtension": "",
								"IsFuelSurchargeApplied": "No",
								"SalesTaxGroup": "",
								"AddressCountryRegionId": "CAN",
								"ContactPersonId": "",
								"CustomerPaymentFineCode": "",
								"BirthCountyCode": "",
								"InvoiceAddress": "InvoiceAccount",
								"PackingMaterialFeeLicenseNumber": "",
								"TransactionPresenceType": "DoesNotApply",
								"PrimaryContactEmailIsIM": "No",
								"PrimaryContactTwitter": "",
								"InvoiceAddressCity": "",
								"IsFinalUser": "No",
								"PrimaryContactEmail": "",
								"DeliveryAddressCounty": "",
								"HasSuframaDiscountPISandCOFINS": "No",
								"InvoiceAddressStreet": "",
								"CURPNumber": "",
								"PrimaryContactLinkedInDescription": "",
								"DeliveryAddressCountryRegionId": "",
								"ItemCustomerGroupId": "",
								"PersonProfessionalTitle": "",
								"SalesSegmentId": "",
								"IsServiceDeliveryAddressBased": "No",
								"PrimaryContactTelexDescription": "",
								"InvoiceAddressDistrictName": "",
								"InvoiceAddressTimeZone": null,
								"SalesAccountNumber": "",
								"PrimaryContactPhoneIsMobile": "No",
								"PrimaryContactFacebookDescription": "",
								"PrimaryContactFaxRecordId": 0,
								"TCSGroup": "",
								"DeliveryAddressLocationId": "",
								"InterCompanyAutoCreateOrders": "No",
								"AddressZipCode": "M5T1V7",
								"GiroTypeProjInvoice": "None",
								"LineOfBusinessId": "",
								"OrganizationPhoneticName": "",
								"DeliveryAddressCountryRegionISOCode": "",
								"CreditCardCVC": "None",
								"DeliveryAddressValidFrom": "1900-01-01T00:00:00Z",
								"GiroTypeAccountStatement": "None",
								"CalculateWithholdingTax": "No",
								"ElectronicInvoiceEAN": "",
								"DeliveryFreightZone": "",
								"PrimaryContactFax": "",
								"TaxExemptNumber": "",
								"DeliveryAddressDescription": "",
								"DeliveryAddressLongitude": 0,
								"BirthPlace": "",
								"AddressCity": "Toronto",
								"PersonInitials": "",
								"DefaultECommerceOperator": "",
								"CentralBankPurposeCode": "",
								"GiroTypeCollectionletter": "None",
								"FullPrimaryAddress": "",
								"OrderEntryDeadline": "",
								"ForeignerId": "",
								"WarehouseIsASNGenerated": "No",
								"AddressLongitude": 0,
								"CustomerType": "None",
								"PrimaryContactLinkedIn": "",
								"PrimaryContactURL": "",
								"IsFreightAccrued": "No",
								"PartyState": "",
								"InvoiceAccount": "",
								"PartyNumber": "000002472",
								"CentralBankPurposeNotes": "",
								"PersonMaritalStatus": "None",
								"CollectionsContactPersonId": "",
								"AddressBuildingComplement": "",
								"AddressLocationId": "",
								"PaymentSchedule": "",
								"PrimaryContactTwitterPurpose": "",
								"GiroType": "None",
								"InvoiceAddressDescription": "",
								"AddressDistrictName": "",
								"DeliveryTerms": "",
								"NumberSequenceGroup": "",
								"PersonChildrenNames": "",
								"PaymentMethod": "",
								"ForeignResident": "No",
								"DeliveryMode": "",
								"PersonProfessionalSuffix": "",
								"OnHoldStatus": "No",
								"AccountStatement": "Always",
								"WarehouseId": "",
								"DestinationCode": "",
								"EInvoiceRegister": "No",
								"IRS1099CIndicator": "No",
								"FrenchSiret": "",
								"PaymentDay": "",
								"BrazilianNIT": "",
								"FederalIndicator": "None",
								"EmployeeResponsibleNumber": "",
								"PersonAnniversaryYear": 0,
								"DefaultInventoryStatusId": "",
								"PrimaryContactEmailDescription": "",
								"AddressTimeZone": null,
								"PrimaryContactPhone": "",
								"PrimaryContactPhoneRecordId": 0,
								"DeliveryAddressCity": "",
								"InvoiceAddressCounty": "",
								"PANReferenceNumber": "",
								"DeliveryAddressStreet": "",
								"SalesCurrencyCode": "CAD",
								"Priority": "AllocationPriority10",
								"IsSalesTaxIncludedInPrices": "No",
								"BrazilianCNPJOrCPF": "",
								"PaymentFactoringAccount": "",
								"PANNumber": "",
								"PrimaryContactTwitterDescription": "",
								"PersonFirstName": "",
								"BrazilianCCM": "",
								"ReceiptEmail": "",
								"TDSGroup": "",
								"MultiLineDiscountCode": "",
								"PersonAnniversaryDay": 0,
								"DefaultDimensionDisplayValue": "",
								"SupplementaryItemGroupId": "",
								"IsWithholdingTaxCalculated": "No",
								"PaymentSpecification": "",
								"AddressRecordId": 0,
								"AddressBooks": "",
								"PrimaryContactEmailPurpose": "",
								"FulfillmentPolicyName": "",
								"SalesDistrict": "",
								"ConsolidationDay": 0,
								"IsExpressBillOfLadingAccepted": "No",
								"CreditCardAddressVerification": "None",
								"InvoiceAddressBuildingComplement": "",
								"AddressState": "ON",
								"IsExcludedFromCollectionFeeCalculation": "No",
								"CustomerPaymentFinancialInterestCode": "",
								"IsTransactionPostedAsShipment": "No",
								"CreditLimitIsMandatory": "No",
								"IsExternallyMaintained": "No",
								"PaymentTermsBaseDays": 0,
								"FiscalCode": "",
								"KnownAs": "",
								"PrimaryContactTelex": "",
								"PaymentBankAccount": "",
								"BrazilianIE": "",
								"PreferentialCustomer": "No",
								"PrimaryContactEmailRecordId": 0,
								"ReceiptOption": "RetailEx3",
								"AddressBrazilianIE": "",
								"PersonAnniversaryMonth": "None",
								"PrimaryContactPhoneExtension": "",
								"InvoiceAddressStreetNumber": "",
								"PrimaryContactPhonePurpose": "",
								"ExportSale": "No",
								"OrganizationNumber": "",
								"InvoicePostingType": "Standard",
								"CreditCardAddressVerificationIsAuthorizationVoidedOnFailure": "No",
								"InvoiceAddressState": "",
								"ReceiptCalendar": "",
								"DeliveryAddressState": "",
								"StateInscription": "",
								"PersonLastNamePrefix": "",
								"SalesReturnTaxGroup": "",
								"PrimaryContactURLDescription": "",
								"CustomerWithholdingContributionType": "Other",
								"IsElectronicInvoice": "No",
								"FederalAgencyLocationCode": "",
								"GiroTypeFreeTextInvoice": "None",
								"DeliveryAddressValidTo": "1900-01-01T00:00:00Z",
								"PersonPhoneticMiddleName": "",
								"OrganizationABCCode": "None",
								"BrazilianCNAE": "",
								"WithholdingTaxGroupCode": "",
								"NAFCode": "",
								"AddressLatitude": 0,
								"TotalDiscountCode": "",
								"AddressLocationRoles": "Business",
								"PaymentCashDiscount": "",
								"DeliveryAddressDistrictName": "",
								"CollectionLetterCode": "None",
								"EInvoiceAttachment": "No",
								"MerchantID": "",
								"CreditRating": "",
								"PrimaryContactFacebook": "",
								"DeliveryAddressBuildingComplement": "",
								"DeliveryAddressStreetNumber": "",
								"InvoiceAddressLongitude": 0,
								"LineDiscountCode": "",
								"PartyCountry": "",
								"InvoiceAddressLatitude": 0,
								"IsInSuframaRegion": "No",
								"IsIncomingFiscalDocumentGenerated": "No",
								"SalesMemo": "",
								"ReliefGroupId": "",
								"IsExcludedFromInterestChargeCalculation": "No",
								"StatisticsGroupId": "",
								"SalesOrderPoolId": "",
								"OrganizationName": "Nick Williams",
								"IsOrderNumberReferenceUsed": "No",
								"CustClassificationId": "ClassGroup",
								"AddressValidTo": "1900-01-01T00:00:00Z",
								"FederalComments": "",
								"PersonGender": "Unknown",
								"PaymentTerms": "",
								"PrimaryContactPhoneDescription": "",
								"AddressPostbox": "",
								"SalesSubsegmentId": "",
								"CustomerRebateGroupId": "",
								"AddressCounty": "",
								"PrimaryContactURLRecordId": 0,
								"IsICMSContributor": "No",
								"InvoiceAddressValidTo": "1900-01-01T00:00:00Z",
								"DeliveryAddressTimeZone": null,
								"InvoiceAddressValidFrom": "1900-01-01T00:00:00Z",
								"CreditLimit": 0,
								"CreditCardAddressVerificationLevel": "Accept",
								"WarehouseIsEntireShipmentFilled": "No",
								"PackingDutyLicense": "",
								"NationalRegistryNumber": "",
								"SiteId": "",
								"InvoiceAddressCountryRegionISOCode": "",
								"IsAllowCreateIndirectOrderLines": "No",
								"PrimaryContactURLPurpose": "",
								"ChargesGroupId": "",
								"PanStatus": "NotAvailable",
								"CommissionSalesGroupId": "",
								"NameAlias": "Nick Williams",
								"PrimaryContactFaxPurpose": "",
								"AddressStreetNumber": "",
								"PersonLastName": "",
								"PaymentIdType": "",
								"VendorAccount": "",
								"AddressCountryRegionISOCode": "",
								"ResidenceForeignCountryRegionId": "",
								"RFCNumber": "",
								"PersonHobbies": "",
								"ElectronicLocationId": "",
								"PrimaryContactLinkedInPurpose": "",
								"InvoiceAddressZipCode": "",
								"IsOneTimeCustomer": "No",
								"ForeignCustomer": "No",
								"CustomerTMAGroupId": "",
								"AddressValidFrom": "1900-01-01T00:00:00Z",
								"OrganizationNumberOfEmployees": 0,
								"CompanyType": "Blank",
								"CustomerGroupId": "TestGroup",
								"GiroTypeInterestNote": "None",
								"DeliveryAddressZipCode": "",
								"DeliveryReason": "",
								"TaxRegistrationId": "",
								"PaymentUseCashDiscount": "Normal",
								"DiscountPriceGroupId": "",
								"AddressDescription": "",
								"SuframaNumber": "",
								"IdentificationNumber": "",
								"AuthorityOffice": "",
								"PersonPhoneticFirstName": "",
								"PrimaryContactTelexPurpose": "",
								"DeliveryAddressLatitude": 0,
								"InvoiceAddressCountryRegionId": "",
								"PrimaryContactFacebookPurpose": "",
								"CompanyChain": "",
								"BrazilianINSSCEI": "",
								"CommissionCustomerGroupId": "",
								"PrimaryContactFaxDescription": "",
								"NatureOfAssessee": "Company",
								"WriteoffReason": "",
								"PersonMiddleName": "",
								"InvoiceAddressLocationId": "",
								"PersonPhoneticLastName": "",
								"LanguageId": "en-us",
								"AddressStreet": "35 McCaul Street",
								"IsPurchRequestUsed": "No",
								"CredManEligibleCreditLimitCurrency": "",
								"CredManCustCreditMaxAlt": 0,
								"CredManStatusReasonId": "",
								"CredManEligibleCreditMax": 0,
								"CredManCustUnlimitedCredit": "No",
								"CredManEligibleCreditLimitDate": "1900-01-01T12:00:00Z",
								"CredManWithAgency": "No",
								"CredManCreditLimitDate": "1900-01-01T12:00:00Z",
								"CredManNextSchedReviewDate": "1900-01-01T12:00:00Z",
								"CredManLastReviewDate": "1900-01-01T12:00:00Z",
								"CredManCustomerSince": "1900-01-01T12:00:00Z",
								"CredManTitleHeld": "No",
								"CredManExclude": "No",
								"CredManBusinessStarted": "1900-01-01T12:00:00Z",
								"CredManNotes": "",
								"CredManCollectionGroupId": "",
								"CredManGroupId": "",
								"CredManAccountStatusId": "",
								"CredManCreditLimitExpiryDate": "1900-01-01T12:00:00Z"
							}
						}
					}
				},
				"security": []
			},
			"get": {
				"tags": [
					"CustomersV3"
				],
				"summary": "Get All Customers",
				"description": "Get All Customers",
				"operationId": "GetCustomers",
				"produces": [
					"application/json"
				],
				"parameters": [
					{
						"name": "Authorization",
						"in": "header",
						"description": "Authorization",
						"required": true,
						"type": "string",
						"x-example": ""
					},
					{
						"name": "Accept",
						"in": "header",
						"description": "Accept",
						"required": false,
						"default": "application/json",
						"type": "string",
						"x-example": ""
					}
				],
				"responses": {
					"200": {
						"description": "All Customers",
						"schema": {
							"$ref": "#/definitions/Customers"
						},
						"examples": {
							"application/json": {
								"@odata.context": "https://trial-jjl7u0.sandbox.operations.dynamics.com/data/$metadata#CustomersV3",
								"value": [
									{
										"@odata.etag": "W/\"JzYxODk5MjYwMiw2ODcxOTQ4NTMwNTswLDA7MSw2ODcxOTQ4NTA4NDsxLDY4NzE5NDgzNzQ0OzEsNjg3MTk1MTg3NjE7MSw2ODcxOTUyMjk3MzswLDA7MCwwOzAsMDswLDA7MSw2ODcxOTQ4NTA4MCc=\"",
										"dataAreaId": "dat",
										"CustomerAccount": "CA00000021",
										"AddressBrazilianCNPJOrCPF": "",
										"PartyType": "Organization",
										"PrimaryContactFaxExtension": "",
										"IsFuelSurchargeApplied": "No",
										"SalesTaxGroup": "",
										"AddressCountryRegionId": "CAN",
										"ContactPersonId": "",
										"CustomerPaymentFineCode": "",
										"BirthCountyCode": "",
										"InvoiceAddress": "InvoiceAccount",
										"PackingMaterialFeeLicenseNumber": "",
										"TransactionPresenceType": "DoesNotApply",
										"PrimaryContactEmailIsIM": "No",
										"PrimaryContactTwitter": "",
										"InvoiceAddressCity": "",
										"IsFinalUser": "No",
										"PrimaryContactEmail": "",
										"DeliveryAddressCounty": "",
										"HasSuframaDiscountPISandCOFINS": "No",
										"InvoiceAddressStreet": "",
										"CURPNumber": "",
										"PrimaryContactLinkedInDescription": "",
										"DeliveryAddressCountryRegionId": "",
										"ItemCustomerGroupId": "",
										"PersonProfessionalTitle": "",
										"SalesSegmentId": "",
										"IsServiceDeliveryAddressBased": "No",
										"PrimaryContactTelexDescription": "",
										"InvoiceAddressDistrictName": "",
										"InvoiceAddressTimeZone": null,
										"SalesAccountNumber": "",
										"PrimaryContactPhoneIsMobile": "No",
										"PrimaryContactFacebookDescription": "",
										"PrimaryContactFaxRecordId": 0,
										"TCSGroup": "",
										"DeliveryAddressLocationId": "",
										"InterCompanyAutoCreateOrders": "No",
										"AddressZipCode": "M5T1V7",
										"GiroTypeProjInvoice": "None",
										"LineOfBusinessId": "",
										"OrganizationPhoneticName": "",
										"DeliveryAddressCountryRegionISOCode": "",
										"CreditCardCVC": "None",
										"DeliveryAddressValidFrom": "1900-01-01T00:00:00Z",
										"GiroTypeAccountStatement": "None",
										"CalculateWithholdingTax": "No",
										"ElectronicInvoiceEAN": "",
										"DeliveryFreightZone": "",
										"PrimaryContactFax": "",
										"TaxExemptNumber": "",
										"DeliveryAddressDescription": "",
										"DeliveryAddressLongitude": 0,
										"BirthPlace": "",
										"AddressCity": "Toronto",
										"PersonInitials": "",
										"DefaultECommerceOperator": "",
										"CentralBankPurposeCode": "",
										"GiroTypeCollectionletter": "None",
										"FullPrimaryAddress": "35 McCaul Street\nToronto, ON M5T1V7\nCAN",
										"OrderEntryDeadline": "",
										"ForeignerId": "",
										"WarehouseIsASNGenerated": "No",
										"AddressLongitude": 0,
										"CustomerType": "None",
										"PrimaryContactLinkedIn": "",
										"PrimaryContactURL": "",
										"IsFreightAccrued": "No",
										"PartyState": "",
										"InvoiceAccount": "",
										"PartyNumber": "000002469",
										"CentralBankPurposeNotes": "",
										"PersonMaritalStatus": "None",
										"CollectionsContactPersonId": "",
										"AddressBuildingComplement": "",
										"AddressLocationId": "000003815",
										"PaymentSchedule": "",
										"PrimaryContactTwitterPurpose": "",
										"GiroType": "None",
										"InvoiceAddressDescription": "",
										"AddressDistrictName": "",
										"DeliveryTerms": "",
										"NumberSequenceGroup": "",
										"PersonChildrenNames": "",
										"PaymentMethod": "",
										"ForeignResident": "No",
										"DeliveryMode": "",
										"PersonProfessionalSuffix": "",
										"OnHoldStatus": "No",
										"AccountStatement": "Always",
										"WarehouseId": "",
										"DestinationCode": "",
										"EInvoiceRegister": "No",
										"IRS1099CIndicator": "No",
										"FrenchSiret": "",
										"PaymentDay": "",
										"BrazilianNIT": "",
										"FederalIndicator": "None",
										"EmployeeResponsibleNumber": "",
										"PersonAnniversaryYear": 0,
										"DefaultInventoryStatusId": "",
										"PrimaryContactEmailDescription": "",
										"AddressTimeZone": null,
										"PrimaryContactPhone": "",
										"PrimaryContactPhoneRecordId": 0,
										"DeliveryAddressCity": "",
										"InvoiceAddressCounty": "",
										"PANReferenceNumber": "",
										"DeliveryAddressStreet": "",
										"SalesCurrencyCode": "CAD",
										"Priority": "AllocationPriority10",
										"IsSalesTaxIncludedInPrices": "No",
										"BrazilianCNPJOrCPF": "",
										"PaymentFactoringAccount": "",
										"PANNumber": "",
										"PrimaryContactTwitterDescription": "",
										"PersonFirstName": "",
										"BrazilianCCM": "",
										"ReceiptEmail": "",
										"TDSGroup": "",
										"MultiLineDiscountCode": "",
										"PersonAnniversaryDay": 0,
										"DefaultDimensionDisplayValue": "",
										"SupplementaryItemGroupId": "",
										"IsWithholdingTaxCalculated": "No",
										"PaymentSpecification": "",
										"AddressRecordId": 68719517686,
										"AddressBooks": "",
										"PrimaryContactEmailPurpose": "",
										"FulfillmentPolicyName": "",
										"SalesDistrict": "",
										"ConsolidationDay": 0,
										"IsExpressBillOfLadingAccepted": "No",
										"CreditCardAddressVerification": "None",
										"InvoiceAddressBuildingComplement": "",
										"AddressState": "ON",
										"IsExcludedFromCollectionFeeCalculation": "No",
										"CustomerPaymentFinancialInterestCode": "",
										"IsTransactionPostedAsShipment": "No",
										"CreditLimitIsMandatory": "No",
										"IsExternallyMaintained": "No",
										"PaymentTermsBaseDays": 0,
										"FiscalCode": "",
										"KnownAs": "",
										"PrimaryContactTelex": "",
										"PaymentBankAccount": "",
										"BrazilianIE": "",
										"PreferentialCustomer": "No",
										"PrimaryContactEmailRecordId": 0,
										"ReceiptOption": "RetailEx3",
										"AddressBrazilianIE": "",
										"PersonAnniversaryMonth": "None",
										"PrimaryContactPhoneExtension": "",
										"InvoiceAddressStreetNumber": "",
										"PrimaryContactPhonePurpose": "",
										"ExportSale": "No",
										"OrganizationNumber": "",
										"InvoicePostingType": "Standard",
										"CreditCardAddressVerificationIsAuthorizationVoidedOnFailure": "No",
										"InvoiceAddressState": "",
										"ReceiptCalendar": "",
										"DeliveryAddressState": "",
										"StateInscription": "",
										"PersonLastNamePrefix": "",
										"SalesReturnTaxGroup": "",
										"PrimaryContactURLDescription": "",
										"CustomerWithholdingContributionType": "Other",
										"IsElectronicInvoice": "No",
										"FederalAgencyLocationCode": "",
										"GiroTypeFreeTextInvoice": "None",
										"DeliveryAddressValidTo": "1900-01-01T00:00:00Z",
										"PersonPhoneticMiddleName": "",
										"OrganizationABCCode": "None",
										"BrazilianCNAE": "",
										"WithholdingTaxGroupCode": "",
										"NAFCode": "",
										"AddressLatitude": 0,
										"TotalDiscountCode": "",
										"AddressLocationRoles": "Business",
										"PaymentCashDiscount": "",
										"DeliveryAddressDistrictName": "",
										"CollectionLetterCode": "None",
										"EInvoiceAttachment": "No",
										"MerchantID": "",
										"CreditRating": "",
										"PrimaryContactFacebook": "",
										"DeliveryAddressBuildingComplement": "",
										"DeliveryAddressStreetNumber": "",
										"InvoiceAddressLongitude": 0,
										"LineDiscountCode": "",
										"PartyCountry": "",
										"InvoiceAddressLatitude": 0,
										"IsInSuframaRegion": "No",
										"IsIncomingFiscalDocumentGenerated": "No",
										"SalesMemo": "",
										"ReliefGroupId": "",
										"IsExcludedFromInterestChargeCalculation": "No",
										"StatisticsGroupId": "",
										"SalesOrderPoolId": "",
										"OrganizationName": "Nick Williams",
										"IsOrderNumberReferenceUsed": "No",
										"CustClassificationId": "ClassGroup",
										"AddressValidTo": "2154-12-31T23:59:59Z",
										"FederalComments": "",
										"PersonGender": "Unknown",
										"PaymentTerms": "",
										"PrimaryContactPhoneDescription": "",
										"AddressPostbox": "",
										"SalesSubsegmentId": "",
										"CustomerRebateGroupId": "",
										"AddressCounty": "",
										"PrimaryContactURLRecordId": 0,
										"IsICMSContributor": "No",
										"InvoiceAddressValidTo": "1900-01-01T00:00:00Z",
										"DeliveryAddressTimeZone": null,
										"InvoiceAddressValidFrom": "1900-01-01T00:00:00Z",
										"CreditLimit": 0,
										"CreditCardAddressVerificationLevel": "Accept",
										"WarehouseIsEntireShipmentFilled": "No",
										"PackingDutyLicense": "",
										"NationalRegistryNumber": "",
										"SiteId": "",
										"InvoiceAddressCountryRegionISOCode": "",
										"IsAllowCreateIndirectOrderLines": "No",
										"PrimaryContactURLPurpose": "",
										"ChargesGroupId": "",
										"PanStatus": "NotAvailable",
										"CommissionSalesGroupId": "",
										"NameAlias": "Nick Williams",
										"PrimaryContactFaxPurpose": "",
										"AddressStreetNumber": "",
										"PersonLastName": "",
										"PaymentIdType": "",
										"VendorAccount": "",
										"AddressCountryRegionISOCode": "CA",
										"ResidenceForeignCountryRegionId": "",
										"RFCNumber": "",
										"PersonHobbies": "",
										"ElectronicLocationId": "",
										"PrimaryContactLinkedInPurpose": "",
										"InvoiceAddressZipCode": "",
										"IsOneTimeCustomer": "No",
										"ForeignCustomer": "No",
										"CustomerTMAGroupId": "",
										"AddressValidFrom": "2021-01-03T22:29:03Z",
										"OrganizationNumberOfEmployees": 0,
										"CompanyType": "Blank",
										"CustomerGroupId": "TestGroup",
										"GiroTypeInterestNote": "None",
										"DeliveryAddressZipCode": "",
										"DeliveryReason": "",
										"TaxRegistrationId": "",
										"PaymentUseCashDiscount": "Normal",
										"DiscountPriceGroupId": "",
										"AddressDescription": "",
										"SuframaNumber": "",
										"IdentificationNumber": "",
										"AuthorityOffice": "",
										"PersonPhoneticFirstName": "",
										"PrimaryContactTelexPurpose": "",
										"DeliveryAddressLatitude": 0,
										"InvoiceAddressCountryRegionId": "",
										"PrimaryContactFacebookPurpose": "",
										"CompanyChain": "",
										"BrazilianINSSCEI": "",
										"CommissionCustomerGroupId": "",
										"PrimaryContactFaxDescription": "",
										"NatureOfAssessee": "Company",
										"WriteoffReason": "",
										"PersonMiddleName": "",
										"InvoiceAddressLocationId": "",
										"PersonPhoneticLastName": "",
										"LanguageId": "en-us",
										"AddressStreet": "35 McCaul Street",
										"IsPurchRequestUsed": "No",
										"CredManEligibleCreditLimitCurrency": "",
										"CredManCustCreditMaxAlt": 0,
										"CredManStatusReasonId": "",
										"CredManEligibleCreditMax": 0,
										"CredManCustUnlimitedCredit": "No",
										"CredManEligibleCreditLimitDate": "1900-01-01T12:00:00Z",
										"CredManWithAgency": "No",
										"CredManCreditLimitDate": "1900-01-01T12:00:00Z",
										"CredManNextSchedReviewDate": "1900-01-01T12:00:00Z",
										"CredManLastReviewDate": "1900-01-01T12:00:00Z",
										"CredManCustomerSince": "1900-01-01T12:00:00Z",
										"CredManTitleHeld": "No",
										"CredManExclude": "No",
										"CredManBusinessStarted": "1900-01-01T12:00:00Z",
										"CredManNotes": "",
										"CredManCollectionGroupId": "",
										"CredManGroupId": "",
										"CredManAccountStatusId": "",
										"CredManCreditLimitExpiryDate": "1900-01-01T12:00:00Z"
									}
								]
							}
						}
					}
				},
				"security": []
			}
		},
		"/CustomerGroups": {
			"post": {
				"tags": [
					"CustomerGroups"
				],
				"summary": "Create a Customer Group",
				"description": "Create a Customer Group",
				"operationId": "CreateCustomerGroup",
				"consumes": [
					"application/json"
				],
				"produces": [
					"application/json"
				],
				"parameters": [
					{
						"name": "CustomerGroup",
						"in": "body",
						"description": "CustomerGroup",
						"required": true,
						"schema": {
							"$ref": "#/definitions/CustomerGroup"
						}
					},
					{
						"name": "Authorization",
						"in": "header",
						"description": "Authorization",
						"required": true,
						"type": "string",
						"x-example": ""
					},
					{
						"name": "Accept",
						"in": "header",
						"description": "Accept",
						"required": false,
						"default": "application/json",
						"type": "string",
						"x-example": ""
					}
				],
				"responses": {
					"200": {
						"description": "OK",
						"schema": {
							"$ref": "#/definitions/CustomerGroup"
						},
						"examples": {
							"application/json": {
								"@odata.context": "https://trial-jjl7u0.sandbox.operations.dynamics.com/data/$metadata#CustomerGroups/$entity",
								"@odata.etag": "W/\"JzEsNjg3MTk0Nzk4MzMn\"",
								"dataAreaId": "dat",
								"CustomerGroupId": "TestGroupx",
								"ClearingPeriodPaymentTermName": "",
								"CustomerAccountNumberSequence": "",
								"DefaultDimensionDisplayValue": "",
								"Description": "Test Customer Groupx",
								"IsSalesTaxIncludedInPrice": "No",
								"WriteOffReason": "",
								"PaymentTermId": "",
								"TaxGroupId": ""
							}
						}
					}
				},
				"security": []
			},
			"get": {
				"tags": [
					"CustomerGroups"
				],
				"summary": "Get All Customer Groups",
				"description": "Get All Customer Groups",
				"operationId": "GetCustomerGroups",
				"produces": [
					"application/json"
				],
				"parameters": [
					{
						"name": "Authorization",
						"in": "header",
						"description": "Authorization",
						"required": true,
						"type": "string",
						"x-example": ""
					},
					{
						"name": "Accept",
						"in": "header",
						"description": "Accept",
						"required": false,
						"default": "application/json",
						"type": "string",
						"x-example": ""
					}
				],
				"responses": {
					"200": {
						"description": "OK",
						"schema": {
							"$ref": "#/definitions/CustomerGroups"
						},
						"examples": {
							"application/json": {
								"@odata.context": "https://trial-jjl7u0.sandbox.operations.dynamics.com/data/$metadata#CustomerGroups",
								"value": [
									{
										"@odata.etag": "W/\"JzEsNjg3MTk0Nzk4MzIn\"",
										"dataAreaId": "dat",
										"CustomerGroupId": "TestGroup",
										"ClearingPeriodPaymentTermName": "",
										"CustomerAccountNumberSequence": "",
										"DefaultDimensionDisplayValue": "",
										"Description": "Test Customer Group",
										"IsSalesTaxIncludedInPrice": "No",
										"WriteOffReason": "",
										"PaymentTermId": "",
										"TaxGroupId": ""
									}
								]
							}
						}
					}
				},
				"security": []
			}
		}
	},
	"definitions": {
		"CustomerGroup": {
			"description": "Model for CustomerGroup",
			"required": [
				"ClearingPeriodPaymentTermName"
			],
			"properties": {
				"ClearingPeriodPaymentTermName": {
					"type": "string",
					"x-example": ""
				},
				"CustomerAccountNumberSequence": {
					"type": "string",
					"x-example": ""
				},
				"CustomerGroupId": {
					"type": "string",
					"x-example": "TestGroup"
				},
				"dataAreaId": {
					"type": "string",
					"x-example": "dat"
				},
				"DefaultDimensionDisplayValue": {
					"type": "string",
					"x-example": ""
				},
				"Description": {
					"type": "string",
					"x-example": "Test Customer Group"
				},
				"IsSalesTaxIncludedInPrice": {
					"type": "string",
					"x-example": "No"
				},
				"PaymentTermId": {
					"type": "string",
					"x-example": ""
				},
				"TaxGroupId": {
					"type": "string",
					"x-example": ""
				},
				"WriteOffReason": {
					"type": "string",
					"x-example": ""
				}
			}
		},
		"CustomerGroups": {
			"description": "Model for CustomerGroups",
			"required": [
				"value"
			],
			"properties": {
				"value": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/CustomerGroup"
					},
					"x-example": "[\r\n  {\r\n    \"@odata.etag\": \"W/\\\"JzEsNjg3MTk0Nzk4MzIn\\\"\",\r\n    \"dataAreaId\": \"dat\",\r\n    \"CustomerGroupId\": \"TestGroup\",\r\n    \"ClearingPeriodPaymentTermName\": \"\",\r\n    \"CustomerAccountNumberSequence\": \"\",\r\n    \"DefaultDimensionDisplayValue\": \"\",\r\n    \"Description\": \"Test Customer Group\",\r\n    \"IsSalesTaxIncludedInPrice\": \"No\",\r\n    \"WriteOffReason\": \"\",\r\n    \"PaymentTermId\": \"\",\r\n    \"TaxGroupId\": \"\"\r\n  }\r\n]"
				}
			}
		},
		"Customers": {
			"description": "Model for Customers",
			"required": [
				"value"
			],
			"properties": {
				"value": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/Customer"
					},
					"x-example": ""
				}
			}
		},
		"Customer": {
			"description": "Customer",
			"required": [
				"AccountStatement"
			],
			"properties": {
				"AccountStatement": {
					"type": "string",
					"x-example": "Always"
				},
				"AddressBooks": {
					"type": "string",
					"x-example": ""
				},
				"AddressBrazilianCNPJOrCPF": {
					"type": "string",
					"x-example": ""
				},
				"AddressBrazilianIE": {
					"type": "string",
					"x-example": ""
				},
				"AddressBuildingComplement": {
					"type": "string",
					"x-example": ""
				},
				"AddressCity": {
					"type": "string",
					"x-example": "Toronto"
				},
				"AddressCountryRegionId": {
					"type": "string",
					"x-example": "CAN"
				},
				"AddressCountryRegionISOCode": {
					"type": "string",
					"x-example": ""
				},
				"AddressCounty": {
					"type": "string",
					"x-example": ""
				},
				"AddressDescription": {
					"type": "string",
					"x-example": ""
				},
				"AddressDistrictName": {
					"type": "string",
					"x-example": ""
				},
				"AddressLatitude": {
					"type": "integer",
					"format": "int32",
					"x-example": "0"
				},
				"AddressLocationId": {
					"type": "string",
					"x-example": ""
				},
				"AddressLocationRoles": {
					"type": "string",
					"x-example": "Business"
				},
				"AddressLongitude": {
					"type": "integer",
					"format": "int32",
					"x-example": "0"
				},
				"AddressPostbox": {
					"type": "string",
					"x-example": ""
				},
				"AddressRecordId": {
					"type": "integer",
					"format": "int32",
					"x-example": "0"
				},
				"AddressState": {
					"type": "string",
					"x-example": "ON"
				},
				"AddressStreet": {
					"type": "string",
					"x-example": "35 McCaul Street"
				},
				"AddressStreetNumber": {
					"type": "string",
					"x-example": ""
				},
				"AddressTimeZone": {
					"type": "string",
					"x-example": ""
				},
				"AddressValidFrom": {
					"type": "string",
					"format": "date-time",
					"x-example": "1900-01-01T00:00:00Z"
				},
				"AddressValidTo": {
					"type": "string",
					"format": "date-time",
					"x-example": "1900-01-01T00:00:00Z"
				},
				"AddressZipCode": {
					"type": "string",
					"x-example": "M5T1V7"
				},
				"AuthorityOffice": {
					"type": "string",
					"x-example": ""
				},
				"BirthCountyCode": {
					"type": "string",
					"x-example": ""
				},
				"BirthPlace": {
					"type": "string",
					"x-example": ""
				},
				"BrazilianCCM": {
					"type": "string",
					"x-example": ""
				},
				"BrazilianCNAE": {
					"type": "string",
					"x-example": ""
				},
				"BrazilianCNPJOrCPF": {
					"type": "string",
					"x-example": ""
				},
				"BrazilianIE": {
					"type": "string",
					"x-example": ""
				},
				"BrazilianINSSCEI": {
					"type": "string",
					"x-example": ""
				},
				"BrazilianNIT": {
					"type": "string",
					"x-example": ""
				},
				"CalculateWithholdingTax": {
					"type": "string",
					"x-example": "No"
				},
				"CentralBankPurposeCode": {
					"type": "string",
					"x-example": ""
				},
				"CentralBankPurposeNotes": {
					"type": "string",
					"x-example": ""
				},
				"ChargesGroupId": {
					"type": "string",
					"x-example": ""
				},
				"CollectionLetterCode": {
					"type": "string",
					"x-example": "None"
				},
				"CollectionsContactPersonId": {
					"type": "string",
					"x-example": ""
				},
				"CommissionCustomerGroupId": {
					"type": "string",
					"x-example": ""
				},
				"CommissionSalesGroupId": {
					"type": "string",
					"x-example": ""
				},
				"CompanyChain": {
					"type": "string",
					"x-example": ""
				},
				"CompanyType": {
					"type": "string",
					"x-example": "Blank"
				},
				"ConsolidationDay": {
					"type": "integer",
					"format": "int32",
					"x-example": "0"
				},
				"ContactPersonId": {
					"type": "string",
					"x-example": ""
				},
				"CreditCardAddressVerification": {
					"type": "string",
					"x-example": "None"
				},
				"CreditCardAddressVerificationIsAuthorizationVoidedOnFailure": {
					"type": "string",
					"x-example": "No"
				},
				"CreditCardAddressVerificationLevel": {
					"type": "string",
					"x-example": "Accept"
				},
				"CreditCardCVC": {
					"type": "string",
					"x-example": "None"
				},
				"CreditLimit": {
					"type": "integer",
					"format": "int32",
					"x-example": "0"
				},
				"CreditLimitIsMandatory": {
					"type": "string",
					"x-example": "No"
				},
				"CreditRating": {
					"type": "string",
					"x-example": ""
				},
				"CredManAccountStatusId": {
					"type": "string",
					"x-example": ""
				},
				"CredManBusinessStarted": {
					"type": "string",
					"format": "date-time",
					"x-example": "1900-01-01T12:00:00Z"
				},
				"CredManCollectionGroupId": {
					"type": "string",
					"x-example": ""
				},
				"CredManCreditLimitDate": {
					"type": "string",
					"format": "date-time",
					"x-example": "1900-01-01T12:00:00Z"
				},
				"CredManCreditLimitExpiryDate": {
					"type": "string",
					"format": "date-time",
					"x-example": "1900-01-01T12:00:00Z"
				},
				"CredManCustCreditMaxAlt": {
					"type": "integer",
					"format": "int32",
					"x-example": "0"
				},
				"CredManCustomerSince": {
					"type": "string",
					"format": "date-time",
					"x-example": "1900-01-01T12:00:00Z"
				},
				"CredManCustUnlimitedCredit": {
					"type": "string",
					"x-example": "No"
				},
				"CredManEligibleCreditLimitCurrency": {
					"type": "string",
					"x-example": ""
				},
				"CredManEligibleCreditLimitDate": {
					"type": "string",
					"format": "date-time",
					"x-example": "1900-01-01T12:00:00Z"
				},
				"CredManEligibleCreditMax": {
					"type": "integer",
					"format": "int32",
					"x-example": "0"
				},
				"CredManExclude": {
					"type": "string",
					"x-example": "No"
				},
				"CredManGroupId": {
					"type": "string",
					"x-example": ""
				},
				"CredManLastReviewDate": {
					"type": "string",
					"format": "date-time",
					"x-example": "1900-01-01T12:00:00Z"
				},
				"CredManNextSchedReviewDate": {
					"type": "string",
					"format": "date-time",
					"x-example": "1900-01-01T12:00:00Z"
				},
				"CredManNotes": {
					"type": "string",
					"x-example": ""
				},
				"CredManStatusReasonId": {
					"type": "string",
					"x-example": ""
				},
				"CredManTitleHeld": {
					"type": "string",
					"x-example": "No"
				},
				"CredManWithAgency": {
					"type": "string",
					"x-example": "No"
				},
				"CURPNumber": {
					"type": "string",
					"x-example": ""
				},
				"CustClassificationId": {
					"type": "string",
					"x-example": "ClassGroup"
				},
				"CustomerAccount": {
					"type": "string",
					"x-example": "CA00000021"
				},
				"CustomerGroupId": {
					"type": "string",
					"x-example": "TestGroup"
				},
				"CustomerPaymentFinancialInterestCode": {
					"type": "string",
					"x-example": ""
				},
				"CustomerPaymentFineCode": {
					"type": "string",
					"x-example": ""
				},
				"CustomerRebateGroupId": {
					"type": "string",
					"x-example": ""
				},
				"CustomerTMAGroupId": {
					"type": "string",
					"x-example": ""
				},
				"CustomerType": {
					"type": "string",
					"x-example": "None"
				},
				"CustomerWithholdingContributionType": {
					"type": "string",
					"x-example": "Other"
				},
				"dataAreaId": {
					"type": "string",
					"x-example": "dat"
				},
				"DefaultDimensionDisplayValue": {
					"type": "string",
					"x-example": ""
				},
				"DefaultECommerceOperator": {
					"type": "string",
					"x-example": ""
				},
				"DefaultInventoryStatusId": {
					"type": "string",
					"x-example": ""
				},
				"DeliveryAddressBuildingComplement": {
					"type": "string",
					"x-example": ""
				},
				"DeliveryAddressCity": {
					"type": "string",
					"x-example": ""
				},
				"DeliveryAddressCountryRegionId": {
					"type": "string",
					"x-example": ""
				},
				"DeliveryAddressCountryRegionISOCode": {
					"type": "string",
					"x-example": ""
				},
				"DeliveryAddressCounty": {
					"type": "string",
					"x-example": ""
				},
				"DeliveryAddressDescription": {
					"type": "string",
					"x-example": ""
				},
				"DeliveryAddressDistrictName": {
					"type": "string",
					"x-example": ""
				},
				"DeliveryAddressLatitude": {
					"type": "integer",
					"format": "int32",
					"x-example": "0"
				},
				"DeliveryAddressLocationId": {
					"type": "string",
					"x-example": ""
				},
				"DeliveryAddressLongitude": {
					"type": "integer",
					"format": "int32",
					"x-example": "0"
				},
				"DeliveryAddressState": {
					"type": "string",
					"x-example": ""
				},
				"DeliveryAddressStreet": {
					"type": "string",
					"x-example": ""
				},
				"DeliveryAddressStreetNumber": {
					"type": "string",
					"x-example": ""
				},
				"DeliveryAddressTimeZone": {
					"type": "string",
					"x-example": ""
				},
				"DeliveryAddressValidFrom": {
					"type": "string",
					"format": "date-time",
					"x-example": "1900-01-01T00:00:00Z"
				},
				"DeliveryAddressValidTo": {
					"type": "string",
					"format": "date-time",
					"x-example": "1900-01-01T00:00:00Z"
				},
				"DeliveryAddressZipCode": {
					"type": "string",
					"x-example": ""
				},
				"DeliveryFreightZone": {
					"type": "string",
					"x-example": ""
				},
				"DeliveryMode": {
					"type": "string",
					"x-example": ""
				},
				"DeliveryReason": {
					"type": "string",
					"x-example": ""
				},
				"DeliveryTerms": {
					"type": "string",
					"x-example": ""
				},
				"DestinationCode": {
					"type": "string",
					"x-example": ""
				},
				"DiscountPriceGroupId": {
					"type": "string",
					"x-example": ""
				},
				"EInvoiceAttachment": {
					"type": "string",
					"x-example": "No"
				},
				"EInvoiceRegister": {
					"type": "string",
					"x-example": "No"
				},
				"ElectronicInvoiceEAN": {
					"type": "string",
					"x-example": ""
				},
				"ElectronicLocationId": {
					"type": "string",
					"x-example": ""
				},
				"EmployeeResponsibleNumber": {
					"type": "string",
					"x-example": ""
				},
				"ExportSale": {
					"type": "string",
					"x-example": "No"
				},
				"FederalAgencyLocationCode": {
					"type": "string",
					"x-example": ""
				},
				"FederalComments": {
					"type": "string",
					"x-example": ""
				},
				"FederalIndicator": {
					"type": "string",
					"x-example": "None"
				},
				"FiscalCode": {
					"type": "string",
					"x-example": ""
				},
				"ForeignCustomer": {
					"type": "string",
					"x-example": "No"
				},
				"ForeignerId": {
					"type": "string",
					"x-example": ""
				},
				"ForeignResident": {
					"type": "string",
					"x-example": "No"
				},
				"FrenchSiret": {
					"type": "string",
					"x-example": ""
				},
				"FulfillmentPolicyName": {
					"type": "string",
					"x-example": ""
				},
				"FullPrimaryAddress": {
					"type": "string",
					"x-example": ""
				},
				"GiroType": {
					"type": "string",
					"x-example": "None"
				},
				"GiroTypeAccountStatement": {
					"type": "string",
					"x-example": "None"
				},
				"GiroTypeCollectionletter": {
					"type": "string",
					"x-example": "None"
				},
				"GiroTypeFreeTextInvoice": {
					"type": "string",
					"x-example": "None"
				},
				"GiroTypeInterestNote": {
					"type": "string",
					"x-example": "None"
				},
				"GiroTypeProjInvoice": {
					"type": "string",
					"x-example": "None"
				},
				"HasSuframaDiscountPISandCOFINS": {
					"type": "string",
					"x-example": "No"
				},
				"IdentificationNumber": {
					"type": "string",
					"x-example": ""
				},
				"InterCompanyAutoCreateOrders": {
					"type": "string",
					"x-example": "No"
				},
				"InvoiceAccount": {
					"type": "string",
					"x-example": ""
				},
				"InvoiceAddress": {
					"type": "string",
					"x-example": "InvoiceAccount"
				},
				"InvoiceAddressBuildingComplement": {
					"type": "string",
					"x-example": ""
				},
				"InvoiceAddressCity": {
					"type": "string",
					"x-example": ""
				},
				"InvoiceAddressCountryRegionId": {
					"type": "string",
					"x-example": ""
				},
				"InvoiceAddressCountryRegionISOCode": {
					"type": "string",
					"x-example": ""
				},
				"InvoiceAddressCounty": {
					"type": "string",
					"x-example": ""
				},
				"InvoiceAddressDescription": {
					"type": "string",
					"x-example": ""
				},
				"InvoiceAddressDistrictName": {
					"type": "string",
					"x-example": ""
				},
				"InvoiceAddressLatitude": {
					"type": "integer",
					"format": "int32",
					"x-example": "0"
				},
				"InvoiceAddressLocationId": {
					"type": "string",
					"x-example": ""
				},
				"InvoiceAddressLongitude": {
					"type": "integer",
					"format": "int32",
					"x-example": "0"
				},
				"InvoiceAddressState": {
					"type": "string",
					"x-example": ""
				},
				"InvoiceAddressStreet": {
					"type": "string",
					"x-example": ""
				},
				"InvoiceAddressStreetNumber": {
					"type": "string",
					"x-example": ""
				},
				"InvoiceAddressTimeZone": {
					"type": "string",
					"x-example": ""
				},
				"InvoiceAddressValidFrom": {
					"type": "string",
					"format": "date-time",
					"x-example": "1900-01-01T00:00:00Z"
				},
				"InvoiceAddressValidTo": {
					"type": "string",
					"format": "date-time",
					"x-example": "1900-01-01T00:00:00Z"
				},
				"InvoiceAddressZipCode": {
					"type": "string",
					"x-example": ""
				},
				"InvoicePostingType": {
					"type": "string",
					"x-example": "Standard"
				},
				"IRS1099CIndicator": {
					"type": "string",
					"x-example": "No"
				},
				"IsAllowCreateIndirectOrderLines": {
					"type": "string",
					"x-example": "No"
				},
				"IsElectronicInvoice": {
					"type": "string",
					"x-example": "No"
				},
				"IsExcludedFromCollectionFeeCalculation": {
					"type": "string",
					"x-example": "No"
				},
				"IsExcludedFromInterestChargeCalculation": {
					"type": "string",
					"x-example": "No"
				},
				"IsExpressBillOfLadingAccepted": {
					"type": "string",
					"x-example": "No"
				},
				"IsExternallyMaintained": {
					"type": "string",
					"x-example": "No"
				},
				"IsFinalUser": {
					"type": "string",
					"x-example": "No"
				},
				"IsFreightAccrued": {
					"type": "string",
					"x-example": "No"
				},
				"IsFuelSurchargeApplied": {
					"type": "string",
					"x-example": "No"
				},
				"IsICMSContributor": {
					"type": "string",
					"x-example": "No"
				},
				"IsIncomingFiscalDocumentGenerated": {
					"type": "string",
					"x-example": "No"
				},
				"IsInSuframaRegion": {
					"type": "string",
					"x-example": "No"
				},
				"IsOneTimeCustomer": {
					"type": "string",
					"x-example": "No"
				},
				"IsOrderNumberReferenceUsed": {
					"type": "string",
					"x-example": "No"
				},
				"IsPurchRequestUsed": {
					"type": "string",
					"x-example": "No"
				},
				"IsSalesTaxIncludedInPrices": {
					"type": "string",
					"x-example": "No"
				},
				"IsServiceDeliveryAddressBased": {
					"type": "string",
					"x-example": "No"
				},
				"IsTransactionPostedAsShipment": {
					"type": "string",
					"x-example": "No"
				},
				"IsWithholdingTaxCalculated": {
					"type": "string",
					"x-example": "No"
				},
				"ItemCustomerGroupId": {
					"type": "string",
					"x-example": ""
				},
				"KnownAs": {
					"type": "string",
					"x-example": ""
				},
				"LanguageId": {
					"type": "string",
					"x-example": "en-us"
				},
				"LineDiscountCode": {
					"type": "string",
					"x-example": ""
				},
				"LineOfBusinessId": {
					"type": "string",
					"x-example": ""
				},
				"MerchantID": {
					"type": "string",
					"x-example": ""
				},
				"MultiLineDiscountCode": {
					"type": "string",
					"x-example": ""
				},
				"NAFCode": {
					"type": "string",
					"x-example": ""
				},
				"NameAlias": {
					"type": "string",
					"x-example": "Nick Williams"
				},
				"NationalRegistryNumber": {
					"type": "string",
					"x-example": ""
				},
				"NatureOfAssessee": {
					"type": "string",
					"x-example": "Company"
				},
				"NumberSequenceGroup": {
					"type": "string",
					"x-example": ""
				},
				"OnHoldStatus": {
					"type": "string",
					"x-example": "No"
				},
				"OrderEntryDeadline": {
					"type": "string",
					"x-example": ""
				},
				"OrganizationABCCode": {
					"type": "string",
					"x-example": "None"
				},
				"OrganizationName": {
					"type": "string",
					"x-example": "Nick Williams"
				},
				"OrganizationNumber": {
					"type": "string",
					"x-example": ""
				},
				"OrganizationNumberOfEmployees": {
					"type": "integer",
					"format": "int32",
					"x-example": "0"
				},
				"OrganizationPhoneticName": {
					"type": "string",
					"x-example": ""
				},
				"PackingDutyLicense": {
					"type": "string",
					"x-example": ""
				},
				"PackingMaterialFeeLicenseNumber": {
					"type": "string",
					"x-example": ""
				},
				"PANNumber": {
					"type": "string",
					"x-example": ""
				},
				"PANReferenceNumber": {
					"type": "string",
					"x-example": ""
				},
				"PanStatus": {
					"type": "string",
					"x-example": "NotAvailable"
				},
				"PartyCountry": {
					"type": "string",
					"x-example": ""
				},
				"PartyNumber": {
					"type": "string",
					"x-example": "000002473"
				},
				"PartyState": {
					"type": "string",
					"x-example": ""
				},
				"PartyType": {
					"type": "string",
					"x-example": "Organization"
				},
				"PaymentBankAccount": {
					"type": "string",
					"x-example": ""
				},
				"PaymentCashDiscount": {
					"type": "string",
					"x-example": ""
				},
				"PaymentDay": {
					"type": "string",
					"x-example": ""
				},
				"PaymentFactoringAccount": {
					"type": "string",
					"x-example": ""
				},
				"PaymentIdType": {
					"type": "string",
					"x-example": ""
				},
				"PaymentMethod": {
					"type": "string",
					"x-example": ""
				},
				"PaymentSchedule": {
					"type": "string",
					"x-example": ""
				},
				"PaymentSpecification": {
					"type": "string",
					"x-example": ""
				},
				"PaymentTerms": {
					"type": "string",
					"x-example": ""
				},
				"PaymentTermsBaseDays": {
					"type": "integer",
					"format": "int32",
					"x-example": "0"
				},
				"PaymentUseCashDiscount": {
					"type": "string",
					"x-example": "Normal"
				},
				"PersonAnniversaryDay": {
					"type": "integer",
					"format": "int32",
					"x-example": "0"
				},
				"PersonAnniversaryMonth": {
					"type": "string",
					"x-example": "None"
				},
				"PersonAnniversaryYear": {
					"type": "integer",
					"format": "int32",
					"x-example": "0"
				},
				"PersonChildrenNames": {
					"type": "string",
					"x-example": ""
				},
				"PersonFirstName": {
					"type": "string",
					"x-example": ""
				},
				"PersonGender": {
					"type": "string",
					"x-example": "Unknown"
				},
				"PersonHobbies": {
					"type": "string",
					"x-example": ""
				},
				"PersonInitials": {
					"type": "string",
					"x-example": ""
				},
				"PersonLastName": {
					"type": "string",
					"x-example": ""
				},
				"PersonLastNamePrefix": {
					"type": "string",
					"x-example": ""
				},
				"PersonMaritalStatus": {
					"type": "string",
					"x-example": "None"
				},
				"PersonMiddleName": {
					"type": "string",
					"x-example": ""
				},
				"PersonPhoneticFirstName": {
					"type": "string",
					"x-example": ""
				},
				"PersonPhoneticLastName": {
					"type": "string",
					"x-example": ""
				},
				"PersonPhoneticMiddleName": {
					"type": "string",
					"x-example": ""
				},
				"PersonProfessionalSuffix": {
					"type": "string",
					"x-example": ""
				},
				"PersonProfessionalTitle": {
					"type": "string",
					"x-example": ""
				},
				"PreferentialCustomer": {
					"type": "string",
					"x-example": "No"
				},
				"PrimaryContactEmail": {
					"type": "string",
					"x-example": ""
				},
				"PrimaryContactEmailDescription": {
					"type": "string",
					"x-example": ""
				},
				"PrimaryContactEmailIsIM": {
					"type": "string",
					"x-example": "No"
				},
				"PrimaryContactEmailPurpose": {
					"type": "string",
					"x-example": ""
				},
				"PrimaryContactEmailRecordId": {
					"type": "integer",
					"format": "int32",
					"x-example": "0"
				},
				"PrimaryContactFacebook": {
					"type": "string",
					"x-example": ""
				},
				"PrimaryContactFacebookDescription": {
					"type": "string",
					"x-example": ""
				},
				"PrimaryContactFacebookPurpose": {
					"type": "string",
					"x-example": ""
				},
				"PrimaryContactFax": {
					"type": "string",
					"x-example": ""
				},
				"PrimaryContactFaxDescription": {
					"type": "string",
					"x-example": ""
				},
				"PrimaryContactFaxExtension": {
					"type": "string",
					"x-example": ""
				},
				"PrimaryContactFaxPurpose": {
					"type": "string",
					"x-example": ""
				},
				"PrimaryContactFaxRecordId": {
					"type": "integer",
					"format": "int32",
					"x-example": "0"
				},
				"PrimaryContactLinkedIn": {
					"type": "string",
					"x-example": ""
				},
				"PrimaryContactLinkedInDescription": {
					"type": "string",
					"x-example": ""
				},
				"PrimaryContactLinkedInPurpose": {
					"type": "string",
					"x-example": ""
				},
				"PrimaryContactPhone": {
					"type": "string",
					"x-example": ""
				},
				"PrimaryContactPhoneDescription": {
					"type": "string",
					"x-example": ""
				},
				"PrimaryContactPhoneExtension": {
					"type": "string",
					"x-example": ""
				},
				"PrimaryContactPhoneIsMobile": {
					"type": "string",
					"x-example": "No"
				},
				"PrimaryContactPhonePurpose": {
					"type": "string",
					"x-example": ""
				},
				"PrimaryContactPhoneRecordId": {
					"type": "integer",
					"format": "int32",
					"x-example": "0"
				},
				"PrimaryContactTelex": {
					"type": "string",
					"x-example": ""
				},
				"PrimaryContactTelexDescription": {
					"type": "string",
					"x-example": ""
				},
				"PrimaryContactTelexPurpose": {
					"type": "string",
					"x-example": ""
				},
				"PrimaryContactTwitter": {
					"type": "string",
					"x-example": ""
				},
				"PrimaryContactTwitterDescription": {
					"type": "string",
					"x-example": ""
				},
				"PrimaryContactTwitterPurpose": {
					"type": "string",
					"x-example": ""
				},
				"PrimaryContactURL": {
					"type": "string",
					"x-example": ""
				},
				"PrimaryContactURLDescription": {
					"type": "string",
					"x-example": ""
				},
				"PrimaryContactURLPurpose": {
					"type": "string",
					"x-example": ""
				},
				"PrimaryContactURLRecordId": {
					"type": "integer",
					"format": "int32",
					"x-example": "0"
				},
				"Priority": {
					"type": "string",
					"x-example": "AllocationPriority10"
				},
				"ReceiptCalendar": {
					"type": "string",
					"x-example": ""
				},
				"ReceiptEmail": {
					"type": "string",
					"x-example": ""
				},
				"ReceiptOption": {
					"type": "string",
					"x-example": "RetailEx3"
				},
				"ReliefGroupId": {
					"type": "string",
					"x-example": ""
				},
				"ResidenceForeignCountryRegionId": {
					"type": "string",
					"x-example": ""
				},
				"RFCNumber": {
					"type": "string",
					"x-example": ""
				},
				"SalesAccountNumber": {
					"type": "string",
					"x-example": ""
				},
				"SalesCurrencyCode": {
					"type": "string",
					"x-example": "CAD"
				},
				"SalesDistrict": {
					"type": "string",
					"x-example": ""
				},
				"SalesMemo": {
					"type": "string",
					"x-example": ""
				},
				"SalesOrderPoolId": {
					"type": "string",
					"x-example": ""
				},
				"SalesReturnTaxGroup": {
					"type": "string",
					"x-example": ""
				},
				"SalesSegmentId": {
					"type": "string",
					"x-example": ""
				},
				"SalesSubsegmentId": {
					"type": "string",
					"x-example": ""
				},
				"SalesTaxGroup": {
					"type": "string",
					"x-example": ""
				},
				"SiteId": {
					"type": "string",
					"x-example": ""
				},
				"StateInscription": {
					"type": "string",
					"x-example": ""
				},
				"StatisticsGroupId": {
					"type": "string",
					"x-example": ""
				},
				"SuframaNumber": {
					"type": "string",
					"x-example": ""
				},
				"SupplementaryItemGroupId": {
					"type": "string",
					"x-example": ""
				},
				"TaxExemptNumber": {
					"type": "string",
					"x-example": ""
				},
				"TaxRegistrationId": {
					"type": "string",
					"x-example": ""
				},
				"TCSGroup": {
					"type": "string",
					"x-example": ""
				},
				"TDSGroup": {
					"type": "string",
					"x-example": ""
				},
				"TotalDiscountCode": {
					"type": "string",
					"x-example": ""
				},
				"TransactionPresenceType": {
					"type": "string",
					"x-example": "DoesNotApply"
				},
				"VendorAccount": {
					"type": "string",
					"x-example": ""
				},
				"WarehouseId": {
					"type": "string",
					"x-example": ""
				},
				"WarehouseIsASNGenerated": {
					"type": "string",
					"x-example": "No"
				},
				"WarehouseIsEntireShipmentFilled": {
					"type": "string",
					"x-example": "No"
				},
				"WithholdingTaxGroupCode": {
					"type": "string",
					"x-example": ""
				},
				"WriteoffReason": {
					"type": "string",
					"x-example": ""
				}
			}
		}
	},
	"securityDefinitions": {},
	"security": [],
	"tags": [
		{
			"name": "CustomerGroups",
			"description": "Operations about CustomerGroups"
		},
		{
			"name": "CustomersV3",
			"description": "Operations about CustomersV3"
		}
	]
}